version: "3.9"

services:

  gateway:
    image: nginx
    ports:
      - "8889:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - login-web

  login-web:
    image: nginx
    volumes:
      - ./web:/usr/share/nginx/html

  node-app:
    image: node:18
    container_name: zerotrust-web
    working_dir: /app
    volumes:
      - ./server:/app
    command: sh -c "npm install && node server.js"
    ports:
      - "3001:3001"

  prometheus:
    image: prom/prometheus
    container_name: zerotrust-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: zerotrust-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  mongo:
    image: mongo
    container_name: zerotrust-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  grafana-storage:
  mongo-data: