{
 "title": "Zero Trust Security Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Login Attempts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(login_attempts_total)" }
   ]
  },
  {
   "title": "Successful Logins",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "(login_success_total)" }
   ]
  },
  {
   "title": "Failed Logins",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "sum(login_fail_total)" }
   ]
  },
  {
   "title": "HTTP Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])" }
   ]
  },
  {
   "title": "ATTACK DETECTED",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(attack_detected_total)" }
   ]
  },
  {
   "title": "SQL Injection",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 9 },
   "targets": [
    {
     "expr": "sum(attack_sql_injection_total)"
    }
   ]
  },
  {
   "title": "Brute Force Attacks",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 13 },
   "targets": [
    { "expr": "sum(attack_bruteforce_total)" }
   ]
  },
  {
   "title": "XSS Attacks",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 17 },
   "targets": [
    { "expr": "sum(attack_xss_total)" }
   ]
  }
 ]
}