events {}

http {

  # 🔥 Rate limit (กัน brute force / bot)
  limit_req_zone $binary_remote_addr zone=one:10m rate=5r/s;

  server {
    listen 80;

    # =========================
    # 🔥 BLOCK ATTACK
    # =========================

    # 🔥 Block SQL Injection
    if ($request_uri ~* "(union|select|drop|--|#|or%201=1|or\+1=1|or 1=1|1=1)") {
      return 403;
    }

    # 🔥 Block XSS
    if ($query_string ~* "<script>") {
      return 403;
    }

    # 🔥 Block bad user agent (bot)
    if ($http_user_agent ~* (curl|wget|python)) {
      return 403;
    }

    # =========================
    # 🔥 API (Device Log)
    # =========================

    location /device-log {
      proxy_pass http://zerotrust-web:4000;

      # 🔥 Forward IP จริงไป backend
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # =========================
    # 🔥 FRONTEND
    # =========================

    location / {

      # 🔥 Apply rate limit
      limit_req zone=one burst=10 nodelay;

      proxy_pass http://login-web:80;

      # 🔥 Forward real IP
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Host $host;
    }

  }
}