events {}

http {

  server {

    listen 80;

    # block simple SQL injection
    if ($query_string ~* "union|select|drop|or 1=1") {
      return 403;
    }

    location / {
      proxy_pass http://login-web:80;
    }

  }

}